### ISSUE TITLE
class Random should NOT take a function pointer

### ISSUE THREAD

**Issue by Ellie-42** [sphincs/parallel-sphincsplus#20]
This makes it very difficult to interface with other libraries and end-user code. 
I propose instead that the class has a virtual function so that an end user can maintain the same format without causing too much change. This would also enable the use of third party libraries to use their RNG for an end user.

The rdrand.cpp would need minimal adjustment to fit this, and most generators would be able to maintain this as well.

I'm working on implementing this in my own fork.

**Comment by Ellie-42** [comment]
I actually did successfully rewrite the random class to permit polymorphism, however I am still testing this out to see what happens in my own implementation. I'll push it to my own fork when I test out the change

**Comment by sfluhrer** [comment]
I don't quite understand what you're suggesting (not that it's wrong; I literally don't "get it").  In the current code, the user has the option to default to rdrand, or pass in their own function that returns random data, or to rederive the random class and redefine the virtual function (just as you appear to describe).  It's clear I'm missing something; what is it?  Perhaps it is that I used operator() as the name of the virtual function that you believe is nonobvious?

**Comment by sfluhrer** [comment]
Requested functionality already present
